### ISSUE TITLE
Wrong spelling of package name in README

### ISSUE THREAD

**Issue by faahim** [mittnavnermike/gatsby-plugins#2]
Hi Mike,

Thanks for the great plugin! I was trying to extract image colours using some other packages and was having a tough time. Being able to query the colour in Graphql makes it so much more convenient and easy in Gatsby environment. Thanks for creating this! :smile: 

However, when trying to install it, yarn was throwing a 404 error and I noticed the package as actually named `gatsby-plugin-extract-image-colors` on both npm and yarn. Whereas it says `gatsby-plugin-extract-image-color` in the README (the `s` at the end was missing). I was just copy-pasting the commands and hence the error.

Thought I'd update the README so that others can install this amazing plugin easily without any confusion. Here's a little PR: #1 

Thanks again! :slightly_smiling_face:

**Comment by Coderwelsch** [comment]
Thank you very much! I also ran into this sneaky issue. You saved me!

**Comment by faahim** [comment]
Hehe, no problem! :smile: 

I just hope @mittnavnermike would notice this so others wouldn't have the problem :slightly_smiling_face:

**Comment by mittnavnermike** [comment]
Great find @faahim. Thank you for this!
