### ISSUE TITLE
Plugin only works when video files are accessible through API

### ISSUE THREAD

**Issue by chrisgrabinski** [mittnavnermike/gatsby-plugins#5]
The plugin `gatsby-source-vimeo-all` only works when video files are accessible through API. This means that it will always break if used with accounts on the Free/Plus plan, where video files are not available through the API. It will also break if `video_files` is not inside the scope of the access token.

At the moment, a warning is being shown in the console but it would probably better to just allow the plugin to work, even if there aren't any video files available.

Edit: Sorry this is regarding `gatsby-source-vimeo-all`, I'm not sure how to mark this in a mono repo. 🙃

**Comment by mittnavnermike** [comment]
Merged 👍
