### ISSUE TITLE
[gatsby-plugin-extract-image-colors] Add other queries other than file

### ISSUE THREAD

**Issue by nandorojo** [mittnavnermike/gatsby-plugins#9]
Hey, super awesome library idea! I was hoping to use this for images from the shopify source...is there any way to pull in colors from sources other than `file`?

**Comment by el-j** [comment]
hi, i had the same issue. i solved it by getting the pictures on build time. so i create a remoteFileNode with gatby and the image is fetched before the plugin is used. see gatsby-source-filesystem helper functions:
https://www.gatsbyjs.com/plugins/gatsby-source-filesystem/

**Comment by mittnavnermike** [comment]
I agree. I would do the same as @el-j  did. Seems better if this plugin only concerns itself with images contained in gatsby.
